import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/features/navigation/Navbar";
import Footer from "@/features/navigation/Footer";
import UserProviderContainer from "@/context/UserProviderContainer";
import { Toaster } from "react-hot-toast";
import { getCurrentUser } from "@/lib/auth/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProviderContainer>
          <div className="flex flex-col items-stretch min-h-screen">
            <Navbar
              user={{
                firstName: user?.firstName,
                lastName: user?.lastName,
                email: user?.email,
              }}
            />
            {children}
            <Footer />
            <Toaster />
          </div>
        </UserProviderContainer>
      </body>
    </html>
  );
}
